name: wf-dev-build
on:
  push:
    branches:
      - develop

jobs:
  dev-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"

  dev-dep-job:
    permissions:
      pages: write
      id-token: write
    needs: dev-build-job
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{github.token}}